name:                demotion-examples
version:             0.1.0.0
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

ghc-options:
- -Wall
dependencies:
- base >= 4.7 && < 5
- type-natural
- ghc-typelits-presburger
- transformers
- mtl
- these

library:
  source-dirs: src

executables: {}

tests: {}
