# This is a basic workflow to help you get started with Actions

name: English Paper

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  WORKDIR: paper
  JOBNAME: demotion-paper
  ARTIFACT_NAME: Paper
  PAGE_LOWERBOUND: 1 # 10 # Disabled for now, as we haven't actually started this project!
  PAGE_UPPERBOUND: 13 # As reference is excluded from the page count.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on:  ubuntu-18.04
    container: docker://konn/texlive2020-slim:20201227.4

    steps:
      - uses: actions/checkout@v2
      - name: Cache
        id: tex-cache
        uses: actions/cache@v2.1.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            ${{env.WORKDIR}}/${{env.JOBNAME}}.fdb_latexmk
            ${{env.WORKDIR}}/.latex/
            ${{env.WORKDIR}}/_minted-demotion-paper

          # An explicit key for restoring and saving the cache
          key: ${{env.JOBNAME}}-${{github.ref}}-${{ runner.os }}-${{ hashFiles('**/*.tex', '**/*.sty', '**/*.fdb_latexmk', 'extract-generateds.lua') }}
          restore-keys: |
            ${{env.JOBNAME}}-${{github.ref}}-${{ runner.os }}-
            ${{env.JOBNAME}}-${{github.ref}}-
            ${{env.JOBNAME}}-master-
      - name: Create .latex directory if missing
        run: |
          [ -d ${GITHUB_WORKSPACE}/${WORKDIR}/.latex ] || mkdir -p ${GITHUB_WORKSPACE}/${WORKDIR}/.latex
      - name: Restore latex files
        run: |
          cd $GITHUB_WORKSPACE/${WORKDIR}
          if [ -n "$(find .latex/ -mindepth 1 -maxdepth 1)" ]; then
            cp -r .latex/* .
          else
            echo "::warn::No .latex/ directory found. skip"
          fi
      - name: Install pygments
        run: |
          apt-get update && apt-get install -y python3-pygments
      - name: Dry-run pygmentize
        run: |
          /usr/bin/pygmentize -V
      - name: Typeset it
        run: |
          cd ${GITHUB_WORKSPACE}/${WORKDIR}
          ls
          latexmk -pdflua ${JOBNAME}.tex
      
      - name: Store latex generated files
        run: |
          cd ${GITHUB_WORKSPACE}/${WORKDIR}
          ls
          for fdb in $(find . -name "*.fdb_latexmk"); do
              for i in $(texlua ${GITHUB_WORKSPACE}/ci-resources/extract-generateds.lua <$fdb); do
                echo "::debug::cp $(dirname $fdb)/$i .latex/$(dirname $fdb)/$i"
                cp $(dirname $fdb)/$i .latex/$(dirname $fdb)/$i
              done
          done

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ${{env.WORKDIR}}/${{env.JOBNAME}}.pdf
          if-no-files-found: error # optional, defaule is warn
          retention-days: 90

  lint:
    runs-on: ubuntu-18.04
    container: docker://konn/poppler-only:latest
    
    needs:
    - build
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.7
      with:
        # Artifact name
        name: ${{env.ARTIFACT_NAME}}
        # Destination path
        path: .
    - name: Tell me your pages
      run: |
        PAGES=$(pdfinfo ${JOBNAME}.pdf | grep "Pages:" | cut -d ':' -f2 | sed 's/[ \t]*//g')
        if [ ${PAGE_LOWERBOUND} -le ${PAGES} -a ${PAGES} -le ${PAGE_UPPERBOUND} ]; then
          echo "OK: Current pages ${PAGES} satisfies range."
        else
          echo "::error::Current page count ${PAGES} exceeds range ${PAGE_LOWERBOUND}..${PAGE_UPPERBOUND}!"
          exit 1
        fi

  # Generates arXiv compatible tarball
  arxiv:
    runs-on:  ubuntu-18.04
    container: docker://konn/texlive2020-slim:20201227.4
    env:
      JOBNAME: demotion-paper

    steps:
      - uses: actions/checkout@v2
      - name: Cache
        id: tex-cache
        uses: actions/cache@v2.1.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            ${{env.WORKDIR}}/${{env.JOBNAME}}.fdb_latexmk
            ${{env.WORKDIR}}/.latex/
            ${{env.WORKDIR}}/_minted-${{env.JOBNAME}}

          # An explicit key for restoring and saving the cache
          key: ${{env.JOBNAME}}-${{github.ref}}-${{ runner.os }}-${{ hashFiles('**/*.tex', '**/*.sty', '**/*.fdb_latexmk', 'extract-generateds.lua') }}
          restore-keys: |
            ${{env.JOBNAME}}-${{github.ref}}-${{ runner.os }}-
            ${{env.JOBNAME}}-${{github.ref}}-
            ${{env.JOBNAME}}-master-
      - name: Create .latex directory if missing
        run: |
          [ -d ${GITHUB_WORKSPACE}/${WORKDIR}/.latex ] || mkdir -p ${GITHUB_WORKSPACE}/${WORKDIR}/.latex
      - name: Restore latex files
        run: |
          cd $GITHUB_WORKSPACE/${WORKDIR}
          if [ -n "$(find .latex/ -mindepth 1 -maxdepth 1)" ]; then
            cp -r .latex/* .
          else
            echo "::warn::No .latex/ directory found. skip"
          fi
      - name: Install pygments
        run: |
          apt-get update && apt-get install -y python3-pygments

      - name: Modifies latex files so that it generates appropriate cache
        run: |
          cd ${GITHUB_WORKSPACE}/${WORKDIR}
          sed -i 's/\\usepackage{minted}/\\usepackage[finalizecache]{minted}/' syntax.tex
          sed -i 's/\[gray,prologue\]{xcolor}/[prologue]{xcolor}/' acmart-preload-hook.tex
          sed -i 's/\[gray,prologue\]{xcolor}/[prologue]{xcolor}/' config.tex
          sed -i 's/\\documentclass\[sigplan,review\]{acmart}/\\documentclass[sigplan,nonacm]{acmart}/' demotion-paper.tex
          sed -i -e 's/^% *\(\\\(author\|email\|affiliation\|institution\|streetaddress\|city\|state\|country\|postcode\)\)/\1/g' demotion-paper.tex
          sed -i 's/lualatex/pdflatex/g' .latexmkrc

      - name: Typeset it (with pdflatex)
        run: |
          cd ${GITHUB_WORKSPACE}/${WORKDIR}
          ls
          grep -A 10 'author{' demotion-paper.tex
          latexmk -pdf ${JOBNAME}.tex

      - name: Store latex generated files
        run: |
          cd ${GITHUB_WORKSPACE}/${WORKDIR}
          ls
          for fdb in $(find . -name "*.fdb_latexmk"); do
              for i in $(texlua ${GITHUB_WORKSPACE}/ci-resources/extract-generateds.lua <$fdb); do
                echo "::debug::cp $(dirname $fdb)/$i .latex/$(dirname $fdb)/$i"
                cp $(dirname $fdb)/$i .latex/$(dirname $fdb)/$i
              done
          done

      - name: Modifies latex files so that it uses appropriate minted cache
        run: |
          cd ${GITHUB_WORKSPACE}/${WORKDIR}
          sed -i 's/\\usepackage\[finalizecache\]{minted}/\\usepackage[frozencache]{minted}/' syntax.tex

      - name: Creates tarball
        run: |
          rm -rf ${{env.WORKDIR}}/*.pdf
          tar czf ${{env.JOBNAME}}.tar.gz --directory=${{env.WORKDIR}} --exclude=${{env.WORKDIR}}/.latex .

      - name: Checks that generated tarball generates appropriate output without -shell-escape
        run: |
          mkdir -p ${{env.JOBNAME}}-testing
          tar xzf ${{env.JOBNAME}}.tar.gz --directory=${{env.JOBNAME}}-testing
          cd ${{env.JOBNAME}}-testing
          ls
          grep minted syntax.tex
          pdflatex ${{env.JOBNAME}}.tex -shell-escape -file-line-error -interaction=nonstopmode -halt-on-error

      - name: Upload an arXiv tarball
        uses: actions/upload-artifact@v2.2.1
        with:
          name: demotion-arxiv
          path: ${{env.JOBNAME}}.tar.gz
          if-no-files-found: error # optional, default is warn
          retention-days: 90

      - name: Upload an arXiv preview
        uses: actions/upload-artifact@v2.2.1
        with:
          name: demotion-arxiv-preview
          path: ${{env.JOBNAME}}-testing/${{env.JOBNAME}}.pdf
          if-no-files-found: error # optional, default is warn
          retention-days: 90
