# This is a basic workflow to help you get started with Actions

name: Supplement

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gen-source:
    runs-on: ubuntu-18.04
    env: 
      STACK_ROOT: "${GITHUB_WORKSPACE}/.stack-root"
    steps:
    - uses: actions/checkout@v2
    - name: Cache .stack-work
      uses: actions/cache@v2.1.3
      with: 
        path: |
          gen-supplement/.stack-work
          ${GITHUB_WORKSPACE}/.stack-root
        key: gensupplement-${{github.ref}}-${{ hashFiles('gen-supplement/**.hs') }}-${{ hashFiles('gen-supplement/**.hs') }}-${{ hashFiles('demotion-examples/**/*') }}
        restore-keys: |
            gensupplement-${{github.ref}}-${{ hashFiles('gen-supplement/**.hs') }}-
            gensupplement-${{github.ref}}-
            gensupplement-master-
    - name: Setup Stack
      uses: haskell/actions/setup@v1.2
      with:
        enable-stack: true
        stack-no-global: true
    - name: Generate supplement.tex
      run: |
        cd gen-supplement
        stack run -- ../demotion-examples
    - name: Upload Raw TeX
      uses: actions/upload-artifact@v2.2.1
      with:
        name: "Supplement-Raw"
        path: "gen-supplement/supplement.tex"
        if-no-files-found: error # optional, defaule is warn
        retention-days: 90

  typeset:
    needs:
    - gen-source
    runs-on:  ubuntu-18.04
    container: docker://konn/texlive2020-slim:20201227.4

    steps:
      - uses: actions/checkout@v2
      - name: Cache
        id: tex-cache
        uses: actions/cache@v2.1.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            _minted-supplement

          # An explicit key for restoring and saving the cache
          key: supplement-${{github.ref}}-${{ hashFiles('demotion-examples/**/*') }}
          restore-keys: |
            supplement-${{github.ref}}-
            supplement-master-
      - name: Install pygments
        run: |
          apt-get update && apt-get install -y python3-pygments
      - name: Typeset it
        run: |
          cd ${GITHUB_WORKSPACE}/${WORKDIR}
          ls
          latexmk -pdflua ${JOBNAME}.tex
      
      - name: Download a Generated supplements
        uses: actions/download-artifact@v2.0.7
        with:
          # Artifact name
          name: Supplement-Raw
          # Destination path
          path: .

      - name: Upload a Supplement PDF
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Supplement PDF
          path: supplement.pdf
          if-no-files-found: error # optional, defaule is warn
          retention-days: 90
